author = "Rolfe Power"

[datasets.de430]
filename = "de430.bsp"
url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp"
description = "standard planetary ephemeris"

[datasets.naif0012]
filename = "naif0012.tls"
description = "standard leap second kernel"
url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls"

[datasets.mar097]
filename = "mar097.bsp"
description = "natural body satellite ephemeris file for Mars"
url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/mar097.bsp"

[datasets.cspice-linux]
filename =  "cspice.tar.Z"
description = "NAIF SPICE toolkit for C programming language, linux edition (64 bit)"
url = "http://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z"

[datasets.cspice-windows]
filename = "cspice.zip"
description = "NAIF SPICE toolkit for C programming language, windows MVVC edition (64 bit)"
url = "http://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Windows_VisualC_64bit/packages/cspice.zip"
