export EDITOR="nvim"
export VISUAL="nvim"

export ZDOTDIR="$HOME/.config/zsh"

export HISTFILE="$HOME/.cache/zsh-history"
export HISTSIZE=10000
export SAVEHIST=10000

export JULIA_DEPOT_PATH="$HOME/.local/depot/julia"
