#!/usr/bin/bash

eval $(dbus-launch --sh-syntax)
sxhkd &
feh --recursive  --no-fehbg --bg-scale ~/Dropbox/Media/Pictures/wallpapers/hedi-alija-V21dkuL8dnM-unsplash.jpg &
emacs --daemon &
mpd
wmname LG3D
xsetroot -cursor_name left_ptr
xrdb ~/.Xresources

flatpak run com.dropbox.Client &
flameshot &


bspc config border_width         3
bspc config window_gap          10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a matplotlib state=floating

bspc monitor -d I II III IV V VI VII VIII IX X
picom --config $HOME/.config/picom/picom.conf -b &
$HOME/.config/polybar/launch.sh
