#!/usr/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.gtkrc-2.0
flatpak run com.dropbox.Client &
flameshot &

if [ -e "$HOME/.fehbg" ]; then
    source "$HOME/.fehbg"
else
    feh --bg-fill '/home/rpower/Pictures/wallpapers/current'
fi

compton -b

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a matplotlib state=floating
