# ---------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
#                             BASIC CONFIGURATION                              #
# ---------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------- #

# Faster command sequences
set -s escape-time 10 

# Mouse interactivity
set -g mouse on

# Enable italics
set -g default-terminal "tmux-256color"

# Start numbering at 1
set -g base-index 1        # Window
setw -g pane-base-index 1  # Pane

# Renumber windows on window close
set -g renumber-windows on

# Rename window to reflect current program
setw -g automatic-rename on

# Set terminal title
set -g set-titles on

# Redraw status line every 10 seconds
set -g status-interval 11

# Longer history
set -g history-limit 5000

# ---------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
#                          KEYBINDING CONFIGURATION                            #
# ---------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------- #

# Create a new session
bind C-c new-session

# vim-like pane traversal
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# Pane Resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 3

# Window Navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# Use C-a as prefix rather than C-b
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split current window horizontally
bind - split-window -v
# split current window vertically
bind _ split-window -h

# Popup terminal
# bind C-t display-popup -CE "$SHELL"
